# Generated by Django 4.2.7 on 2026-01-19 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('qmodel', '0002_stepconfig_function'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobCreationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pipeline_id', models.IntegerField()),
                ('recording_config', models.JSONField()),
                ('job_env_preset', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('job', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creation_log', to='qmodel.job')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
