# Generated by Django 5.2.1 on 2025-10-05 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('qmodel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pipeline',
            fields=[
                ('pipeline_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField(help_text='Description of the pipeline')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Pipeline',
                'verbose_name_plural': 'Pipelines',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PipelineStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, help_text='Execution order within the pipeline')),
                ('depends_on', models.ForeignKey(blank=True, help_text='Optional: The job step this pipeline step depends on', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dependent_pipeline_steps', to='qmodel.jobstep')),
                ('pipeline', models.ForeignKey(help_text='The pipeline this step belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='pipeline.pipeline')),
                ('step_config', models.ForeignKey(help_text='The configuration for this step', on_delete=django.db.models.deletion.CASCADE, related_name='pipeline_steps', to='qmodel.stepconfig')),
            ],
            options={
                'verbose_name': 'Pipeline Step',
                'verbose_name_plural': 'Pipeline Steps',
                'ordering': ['pipeline', 'order'],
                'unique_together': {('pipeline', 'step_config')},
            },
        ),
    ]
