# Generated by Django 4.2.7 on 2026-01-28 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qmodel', '0003_alter_stepconfig_config_block'),
        ('pipeline', '0004_remove_pipelinestep_config_remove_pipelinestep_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pipelinestep',
            name='config_block',
            field=models.ForeignKey(blank=True, help_text='Step-specific configuration', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pipeline_steps_config', to='qmodel.stepconfig', to_field='config_block'),
        ),
    ]
