# Generated by Django 4.2.7 on 2026-02-02 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0006_remove_pipelinestep_config_block_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pipelinestep',
            name='function',
        ),
    ]
