# ============================================================
# SpikesortingLabHub — Production Image
# Base: Ubuntu (not the slim Python image) so system packages
# like openssl, gcc, and libpq are available for workers.
# ============================================================

FROM ubuntu:24.04

# Prevent interactive prompts during apt-get
ENV DEBIAN_FRONTEND=noninteractive

# ------------------------------------------------------------
# 1. System packages
# ------------------------------------------------------------
RUN apt-get update && apt-get install -y --no-install-recommends \
        python3.13 \
        python3.13-venv \
        python3-pip \
        build-essential \
        libpq-dev \
        openssl \
        ca-certificates \
        curl \
    && rm -rf /var/lib/apt/lists/*

# Make python3 / pip point at 3.13
RUN update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.13 1 \
 && update-alternatives --install /usr/bin/python  python  /usr/bin/python3.13 1

# ------------------------------------------------------------
# 2. App directory
# ------------------------------------------------------------
WORKDIR /app

# ------------------------------------------------------------
# 3. Install Python dependencies before copying source so
#    Docker can cache this layer and skip it on code-only changes.
# ------------------------------------------------------------
COPY requirements.txt .
RUN pip install --no-cache-dir --break-system-packages -r requirements.txt

# ------------------------------------------------------------
# 4. Copy the Django project into the image.
#    .dockerignore excludes node_modules, venvs, __pycache__,
#    secrets, and the bind-mounted runtime directories so the
#    image stays small and never contains sensitive files.
# ------------------------------------------------------------
COPY . .

# ------------------------------------------------------------
# 5. Bind-mount directories — empty placeholders so the container
#    starts cleanly even if host bind mounts are missing.
#    /data        ← trurnasdata (read-only NAS database)
#    /django_db   ← persistentdata (Django SQLite DB + logs)
#    /experiments ← binary recording files (read-only)
# ------------------------------------------------------------
RUN mkdir -p /data /django_db /experiments

# ------------------------------------------------------------
# 6. SSL certificates directory — generated by deploy.sh and
#    bind-mounted at runtime.  Never baked into the image.
# ------------------------------------------------------------
RUN mkdir -p /app/secrets

# ------------------------------------------------------------
# 7. Entrypoint — runs collectstatic + migrations before Gunicorn
#    so env vars (DJANGO_SECRET_KEY etc.) are available.
# ------------------------------------------------------------
COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh
ENTRYPOINT ["/entrypoint.sh"]

# ------------------------------------------------------------
# 8. Expose ports
#    9000 — plain HTTP
#    9443 — HTTPS (Gunicorn with --certfile / --keyfile)
# ------------------------------------------------------------
EXPOSE 9000 9443

# ------------------------------------------------------------
# 9. Default command — passed to entrypoint.sh via exec "$@".
# ------------------------------------------------------------
CMD ["gunicorn", "-c", "gunicorn.conf.py", "labhub.wsgi:application"]
