# ============================================================
# SpikesortingLabHub — Production Image
# Base: Ubuntu (not the slim Python image) so system packages
# like openssl, gcc, and libpq are available for workers.
# ============================================================

FROM ubuntu:24.04

# Prevent interactive prompts during apt-get
ENV DEBIAN_FRONTEND=noninteractive

# ------------------------------------------------------------
# 1. System packages
# ------------------------------------------------------------
RUN apt-get update && apt-get install -y --no-install-recommends \
        python3.13 \
        python3.13-venv \
        python3-pip \
        build-essential \
        libpq-dev \
        openssl \
        ca-certificates \
        curl \
    && rm -rf /var/lib/apt/lists/*

# Make python3 / pip point at 3.13
RUN update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.13 1 \
 && update-alternatives --install /usr/bin/python  python  /usr/bin/python3.13 1

# ------------------------------------------------------------
# 2. App directory
# ------------------------------------------------------------
WORKDIR /app

# ------------------------------------------------------------
# 3. Install Python dependencies before copying source so
#    Docker can cache this layer and skip it on code-only changes.
# ------------------------------------------------------------
COPY requirements.txt .
RUN pip install --no-cache-dir --break-system-packages -r requirements.txt

# ------------------------------------------------------------
# 4. Copy the Django project into the image.
#    .dockerignore excludes node_modules, venvs, __pycache__,
#    secrets, and the bind-mounted runtime directories so the
#    image stays small and never contains sensitive files.
# ------------------------------------------------------------
COPY . .

# ------------------------------------------------------------
# 5. Collect static files (React build + Django admin CSS).
#    WhiteNoise serves from STATIC_ROOT at runtime.
# ------------------------------------------------------------
RUN python manage.py collectstatic --noinput

# ------------------------------------------------------------
# 6. Bind-mount directories expected at runtime.
#    These are created here as empty placeholders so the
#    container starts cleanly even if the host bind mount is
#    missing.  Docker-compose will overlay the real host paths.
#
#    /data          ← NAS_Database (trurnasdata, read-only)
#    /django_db     ← Django_database + logs (persistentdata, read/write)
#    /experiments   ← binary recording files (experiments, read-only)
# ------------------------------------------------------------
RUN mkdir -p /data /django_db /experiments

# ------------------------------------------------------------
# 7. SSL certificates directory — generated by deploy.sh or
#    mounted from the host.  Never baked into the image.
# ------------------------------------------------------------
RUN mkdir -p /app/secrets

# ------------------------------------------------------------
# 8. Entrypoint — runs migrations automatically before Gunicorn
#    starts on every container launch.
# ------------------------------------------------------------
COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh
ENTRYPOINT ["/entrypoint.sh"]

# ------------------------------------------------------------
# 9. Expose ports
#    9000 — plain HTTP (Gunicorn default)
#    9443 — HTTPS (Gunicorn with --certfile / --keyfile)
# ------------------------------------------------------------
EXPOSE 9000 9443

# ------------------------------------------------------------
# 10. Default command — passed to entrypoint, which runs
#     migrations first then execs this.
# ------------------------------------------------------------
CMD ["gunicorn", "-c", "gunicorn.conf.py", "labhub.wsgi:application"]
