# Generated by Django 5.2.4 on 2025-08-05 21:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('job_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('job_env_config', models.JSONField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('fetched', 'Fetched'), ('running', 'Running'), ('finished', 'Finished'), ('failed', 'Failed')], default='pending', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='StepConfig',
            fields=[
                ('config_block_hash', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('config_block', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='JobStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=64)),
                ('function', models.CharField(max_length=64)),
                ('depends_on', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('fetched', 'Fetched'), ('running', 'Running'), ('finished', 'Finished'), ('failed', 'Failed')], default='pending', max_length=32)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qmodel.job')),
                ('config_block_hash', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qmodel.stepconfig')),
            ],
            options={
                'unique_together': {('job', 'identifier')},
            },
        ),
    ]
