# Generated by Django 5.2.1 on 2025-08-18 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qmodel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='identifier',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_env_config',
            field=models.JSONField(default=dict),
        ),
    ]
