# Generated by Django 5.2.4 on 2025-08-04 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qmodel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobstep',
            name='identifier',
            field=models.CharField(max_length=100),
        ),
    ]
