# Generated by Django 5.2.1 on 2026-02-17 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submit_jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='jobcreationlog',
            table='jobs_jobcreationlog',
        ),
    ]
