"""
Django settings for labhub project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-w7ub%5ia5q0bk%(gdht0wn1zmu6e92_*4wsrs3i%9@90u!u=a4"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*", "localhost"]

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "rest_framework.authtoken",
    "job_queue.apps.JobQueueConfig",
    "pipeline_factory.apps.PipelineFactoryConfig",
    "submit_jobs.apps.SubmitJobsConfig",
]
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.TokenAuthentication",
        # "rest_framework.authentication.SessionAuthentication",  # Optional: This needs to be commented out if you want to use only token authentication and not session authentication.
    ],
}

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",  # serves static files via Gunicorn
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "labhub.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "labhub" / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "labhub.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "Django_database" / "db.sqlite3",
    }
}

# DATABASES = {
#     "default": {
#         "ENGINE": "django.db.backends.postgresql",
#         "NAME": "labhubdb",
#         "USER": "labhubuser",
#         "PASSWORD": "labhubpass",
#         "HOST": "localhost",
#         "PORT": "5432",
#     }
# }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "/static/"
# WhiteNoise serves from STATIC_ROOT in all modes (dev and production).
# collectstatic copies files from STATICFILES_DIRS → STATIC_ROOT.
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_DIRS = [
    BASE_DIR / "my-app" / "build",
    BASE_DIR / "labhub" / "templates" / "static",
]
# Compress and cache static files (adds .gz / .br alongside each file)
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",  # Default Django authentication
    "labhub.backends.FreeNASBackend",  # NAS database authentication
]

MEDIA_ROOT = BASE_DIR / "media"
MEDIA_URL = "/media/"

# Directories on the server that are scanned for .bin and .prb/.json data files.
# Override this in a local settings file or environment to point at your actual data paths.
_DEFAULT_DATA_DIRS = ",".join(
    [
        str(BASE_DIR / "experiments"),
        str(BASE_DIR / "experiments" / "probes"),
    ]
)
DATA_DIRS = os.environ.get("DATA_DIRS", _DEFAULT_DATA_DIRS).split(",")

# NAS root — the base path the worker's sslh-cli prepends to every file path.
# Paths stored in the DB are RELATIVE to this root.
# On the Linux server: export NAS_ROOT=/mnt/your_nas_mount_path
# On a local dev machine: leave unset — defaults to BASE_DIR so paths still resolve locally.
NAS_ROOT = os.environ.get("NAS_ROOT", str(BASE_DIR))

# CORS — React is built via `npm run build` and served by Django on port 8000.
# No separate React dev server (port 3000) is used. Add origins here only if
# an external client needs to call the API.
CORS_ALLOWED_ORIGINS = [
    "http://localhost:8000",
    "http://127.0.0.1:8000",
    "https://localhost:8443",
    "https://127.0.0.1:8443",
]

# -----------------------------------------------------------------------------
# SSL / HTTPS security settings
# Only active in production (DEBUG=False).  In development Django's runserver
# does not support SSL and these headers would break the plain-HTTP workflow.
# -----------------------------------------------------------------------------
if not DEBUG:
    # Redirect all plain-HTTP requests to HTTPS at the application layer.
    # When Gunicorn/Nginx terminates SSL upstream, set this to False and use
    # SECURE_PROXY_SSL_HEADER instead so Django trusts the forwarded protocol.
    SECURE_SSL_REDIRECT = True

    # Tell the browser: "only talk to this site over HTTPS for the next hour"
    # Increase max_age to 31536000 (1 year) once HTTPS is proven stable.
    SECURE_HSTS_SECONDS = 3600
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = False  # Flip to True only after testing HSTS fully

    # Cookies must only be sent over HTTPS
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

    # Prevent the browser from MIME-sniffing the content type
    SECURE_CONTENT_TYPE_NOSNIFF = True

    # Enable the browser's XSS filter
    SECURE_BROWSER_XSS_FILTER = True

    # If Gunicorn sits behind a reverse proxy (e.g., Nginx) that sets this
    # header, Django will trust the forwarded protocol rather than the raw one.
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# Enable corsheaders only if the package is installed. This avoids import-time
# errors in environments where django-cors-headers isn't available.
try:
    import importlib

    if importlib.util.find_spec("corsheaders") is not None:
        # insert corsheaders into INSTALLED_APPS and MIDDLEWARE
        if "corsheaders" not in INSTALLED_APPS:
            INSTALLED_APPS.insert(
                INSTALLED_APPS.index("rest_framework") + 1, "corsheaders"
            )
        if "corsheaders.middleware.CorsMiddleware" not in MIDDLEWARE:
            MIDDLEWARE.insert(0, "corsheaders.middleware.CorsMiddleware")
except Exception:
    # If anything goes wrong, skip enabling CORS middleware (safe fallback)
    pass
