# Generated by Django 5.2.1 on 2025-10-24 21:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline_factory', '0001_initial'),
        ('job_queue', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pipelinestep',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='pipelinestep',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='pipelinestep',
            name='depends_on',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.CreateModel(
            name='Recording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bin_file', models.FileField(upload_to='recordings/')),
                ('probe_file', models.FileField(upload_to='probes/')),
                ('sampling_rate', models.FloatField()),
                ('num_channels', models.IntegerField()),
                ('gain_to_uV', models.FloatField()),
                ('offset_to_uV', models.FloatField()),
                ('remove_channels', models.JSONField(default=list)),
                ('bad_channels', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('step_config', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recordings', to='job_queue.stepconfig')),
            ],
            options={
                'verbose_name': 'Recording',
                'verbose_name_plural': 'Recordings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='pipelinestep',
            name='order',
        ),
    ]
