# Generated by Django 4.2.7 on 2026-01-19 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline_factory', '0002_alter_pipelinestep_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipelinestep',
            name='config',
            field=models.JSONField(blank=True, help_text='Step-specific configuration', null=True),
        ),
        migrations.AddField(
            model_name='pipelinestep',
            name='function',
            field=models.CharField(default='', help_text='Step function name', max_length=64),
        ),
        migrations.AddField(
            model_name='pipelinestep',
            name='order',
            field=models.IntegerField(default=0, help_text='Execution order within pipeline'),
        ),
    ]
