# Generated by Django 4.2.7 on 2026-01-28 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job_queue', '0002_stepconfig_function'),
        ('pipeline_factory', '0003_pipelinestep_config_pipelinestep_function_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pipelinestep',
            name='config',
        ),
        migrations.RemoveField(
            model_name='pipelinestep',
            name='id',
        ),
        migrations.RemoveField(
            model_name='pipelinestep',
            name='order',
        ),
        migrations.RemoveField(
            model_name='pipelinestep',
            name='step_config',
        ),
        migrations.AddField(
            model_name='pipelinestep',
            name='config_block',
            field=models.JSONField(blank=True, help_text='Step-specific configuration', null=True),
        ),
        migrations.AddField(
            model_name='pipelinestep',
            name='config_block_hash',
            field=models.ForeignKey(default=1, help_text='The configuration for this step', on_delete=django.db.models.deletion.CASCADE, related_name='pipeline_steps', to='job_queue.stepconfig'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pipelinestep',
            name='pipeline_step_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pipelinestep',
            name='depends_on',
            field=models.JSONField(blank=True, default=list, help_text='Step dependencies (identifiers of prerequisite steps)', null=True),
        ),
        migrations.DeleteModel(
            name='Recording',
        ),
    ]
