# Generated by Django 4.2.7 on 2026-02-02 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job_queue', '0003_alter_stepconfig_config_block'),
        ('pipeline_factory', '0005_alter_pipelinestep_config_block'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pipelinestep',
            name='config_block',
        ),
        migrations.AlterField(
            model_name='pipelinestep',
            name='config_block_hash',
            field=models.ForeignKey(help_text='FK to StepConfig - access both hash and config via this relationship', on_delete=django.db.models.deletion.CASCADE, related_name='pipeline_steps', to='job_queue.stepconfig'),
        ),
    ]
