# Generated by Django 5.2.1 on 2026-02-17 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline_factory', '0007_remove_pipelinestep_function'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='pipeline',
            table='pipeline_pipeline',
        ),
        migrations.AlterModelTable(
            name='pipelinestep',
            table='pipeline_pipelinestep',
        ),
    ]
