# Generated by Django 6.0.4 on 2026-04-10 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_queue', '0005_alter_job_status'),
        ('pipeline_factory', '0008_alter_pipeline_table_alter_pipelinestep_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pipeline',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='pipelinestep',
            name='config_block_hash',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pipeline_steps', to='job_queue.stepconfig'),
        ),
        migrations.AlterField(
            model_name='pipelinestep',
            name='depends_on',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='pipelinestep',
            name='pipeline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='pipeline_factory.pipeline'),
        ),
    ]
