# Generated by Django 6.0.4 on 2026-08-30 20:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MovementSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Untitled Session', max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('subject', models.CharField(blank=True, default='', max_length=255)),
                ('recorded_at', models.DateTimeField(blank=True, null=True)),
                ('sample_rate_hz', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movement_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'movement_analysis_session',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='MovementTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(default='point', max_length=255)),
                ('samples', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='movement_analysis.movementsession')),
            ],
            options={
                'db_table': 'movement_analysis_track',
                'ordering': ['label'],
            },
        ),
    ]
