# Generated by Django 5.2.1 on 2025-11-18 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_queue', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stepconfig',
            name='function',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
