# Generated by Django 4.2.7 on 2026-01-28 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_queue', '0002_stepconfig_function'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stepconfig',
            name='config_block',
            field=models.JSONField(unique=True),
        ),
    ]
