# Generated by Django 5.2.1 on 2026-02-17 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_queue', '0003_alter_stepconfig_config_block'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobstep',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=32),
        ),
        migrations.AlterModelTable(
            name='job',
            table='qmodel_job',
        ),
        migrations.AlterModelTable(
            name='jobstep',
            table='qmodel_jobstep',
        ),
        migrations.AlterModelTable(
            name='stepconfig',
            table='qmodel_stepconfig',
        ),
    ]
